name: "Run tests (required)"
permissions:
  contents: read
on:
  workflow_dispatch:
  merge_group:
  pull_request:

jobs:  
  dotnet-tests:
    runs-on: ubuntu-latest
    name: ".NET Tests & Reports"
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      
    - name: Restore dependencies IriTools
      run: dotnet restore ./src/IriTools.sln
      
    - name: Build IriTools
      run: dotnet build ./src/IriTools.sln --no-restore
      
    - name: Restore dependencies IriToolsNugetTest
      run: dotnet restore src/IriToolsNugetTest/IriToolsNugetTest.sln

    - name: Build IriToolsNugetTest
      run: dotnet build src/IriToolsNugetTest/IriToolsNugetTest.sln --no-restore
    
    - name: Test
      run: |
        dotnet test ./src/IriTools.sln   --no-build --verbosity normal 
        dotnet test src/IriToolsNugetTest/IriToolsNugetTest.sln --no-build --verbosity normal
    